bf16: true
cutoff_len: 1024
dataset: train_1_OneNotes_JSON
ddp_timeout: 180000000
do_train: true
eval_steps: 500
eval_strategy: steps
finetuning_type: lora
gradient_accumulation_steps: 8
learning_rate: 0.0001
logging_steps: 10
lora_target: all
lr_scheduler_type: cosine
max_samples: 1000
model_name_or_path: meta-llama/Meta-Llama-3-8B-Instruct
num_train_epochs: 3.0
output_dir: saves/llama3-8b/lora/sft_0_train_1_OneNotes_JSON
overwrite_cache: true
overwrite_output_dir: true
per_device_eval_batch_size: 1
per_device_train_batch_size: 1
plot_loss: true
preprocessing_num_workers: 16
save_steps: 500
stage: sft
template: llama3
val_size: 0.1
warmup_ratio: 0.1
